### ISSUE TITLE
SQL Server communication failure

### ISSUE THREAD

**Issue by DasGabelhauser** [cubixel/TutorPoint#69]
sometimes when triggering an action involving the SQL server, there is a Communication Link Error.
Severity: 3

**Comment by JADGardner** [comment]
Fixed with the ClientHandler while loop fix.

**Comment by DasGabelhauser** [comment]
still happens.
only happens if things are left alone for a couple of minutes.

**Comment by dmb537** [comment]
Only seen this happen when attempting to update the Live status when an Admin closes the program without logging out/stopping streaming first. Don't have the foggiest idea why.
